poldracklab/fitlins

fitlins/base.py
fitlins/cli/run.py
fitlins/utils/bids.py

The core of this PR is `base.run`, which reads a JSON model description, collects events, creates a nistats design matrix and saves as a TSV.
I've tested this with the following command:
```
fitlins/cli/run.py /data/bids/ds000114 /data/out/ds000114/derivatives run --participant_label 02 -s test --space T1w
```
This assumes:
*  `fmriprep/` directory with `space-T1w` preprocessed BOLD series in `/data/out/ds000114/derivatives`
* `model.json` in `/data/bids/ds000114`
The purpose is here is to demonstrate getting a basic HRF model (confounds are currently not included, though there is a low-pass filter automatically added), and get feedback in terms of whether I'm using pybids reasonably here, how likely the API I've used is to change (I stuck with `pybids.events` and didn't dip into …

Initial behavior

---

.circleci/config.yml
.dockerignore
Dockerfile
README.rst
fitlins/info.py
requirements.txt

Final maintenance work in the run-up to an initial release.
@tyarkoni @adelavega @chrisfilo Let me know if you have urgent outstanding issues that would block release. (I understand that the pybids changes in queue are going to break this.)
Replaces #9. Release branches should be pushed upstream.

REL: 0.0.1

---

fitlins/cli/run.py

@adelavega In case you haven't already done something similar.

ENH: Add trivial dataset_description.json

---

fitlins/interfaces/bids.py

Any other issues that need consideration here?
Fixes #40.

FIX: Force string input to snake_to_camel

---

fitlins/workflows/base.py

FIX: Include run in derivative names

---

CHANGES.rst
fitlins/workflows/base.py

REL: 0.0.5

---

CHANGES.rst
tools/update_changes.sh

Hotfix release before breaking everything with #30.

REL: 0.0.6

---

README.rst

Also update the `--help` output to include all options.
Closes #60.

DOC: Example model

---

fitlins/__about__.py
fitlins/cli/run.py
fitlins/interfaces/bids.py
fitlins/utils/bids.py
fitlins/viz/reports.py
fitlins/workflows/base.py
requirements.txt

This PR is meant to be a back-and-forth with @adelavega's #86. Whichever gets merged is fine, but rather than make PRs against each other's branches, this might give us a little more flexibility to work without waiting on each other.
Closes #64.
Closes #86.

[WIP] ENH: Dynamic multi-level support

---

fitlins/cli/run.py
fitlins/workflows/base.py

Related to PRs #92 and #94.
The 'desc' keyword gets included as a parameter in init_fitlins_wf.

ENH: Include desc parameter in init_fitlins_wf 

---

fitlins/cli/run.py
fitlins/interfaces/bids.py

Related to PR #93.
Introduces an option for "no space", if filename does not contain a space specification.

ENH: Allow for an empty (None) space

---

fitlins/interfaces/visualizations.py
fitlins/workflows/base.py

Default plots look pretty bad, particularly for first-level stats.

ENH: Plotting improvements

---

fitlins/interfaces/visualizations.py

I don't know what I was thinking in #89.
Fixes #107.

FIX: Blue is negative, red is positive

---

fitlins/cli/run.py
fitlins/interfaces/bids.py
fitlins/workflows/base.py

ENH: Re-enable analysis level selection

---

fitlins/cli/run.py

* dump crashfiles to user-set working directory
* save crashfiles to text

enh: show crashfiles some love

---

.zenodo.json

@kfinc @rciric @mgxd I'm adding you to the .zenodo.json file. Could you update the spelling of your names to how you'd want them listed on a publication (Last, First), and update your affiliation and ORCID? You can use the suggestion feature or just post them in this thread.

MNT: Add names to Zenodo

---

fitlins/interfaces/bids.py

FIX: Drop lower level metadata at higher levels

---

setup.cfg

MAINT: Drop Python 3.5 support

---

.circleci/config.yml
fitlins/workflows/base.py

Starting by making sure that I can grab data with Datalad.
Closes #68.
Addresses #82.

CI: Test FitLins on OpenNeuro DS000003, preprocessed with fMRIPrep 1.3.2

---

fitlins/workflows/base.py

Might as well knock this one out. Currently has an index column that should be removed to be BIDSy.
Closes #47.

ENH: Save design matrix as TSV to output directory

---

.readthedocs.yml
CHANGES.rst
Makefile
docs/Makefile
docs/changes.rst
docs/conf.py
docs/index.rst
docs/make.bat
fitlins/interfaces/bids.py
setup.cfg

DOC: Create Sphinx documentation with API autodocs

---

docs/Makefile
docs/conf.py
setup.cfg

RTD is down, so leaving this open to remind me to check back in in the morning.

DOC: Build API docs on RTD

---

.circleci/config.yml
README.rst
docs/citing.rst
docs/conf.py
docs/index.rst
docs/license.rst
docs/links.rst
docs/model.rst
docs/support.rst
docs/usage.rst
setup.cfg
setup.py

I'll also add in some discussion of models.

 DOC: Flesh out documentation

---

fitlins/workflows/base.py

Fixes #156 
Checks length of Model steps, not model length.

Fix: Smoothing level, check length 

---

docs/examples/models.rst
examples/models/ds000117/models/model-001_smdl.json

ENH: Add ds000117 model

---

fitlins/interfaces/bids.py
setup.cfg
setup.py

MAINT: Update pybids dependency, package name

---

fitlins/interfaces/bids.py
fitlins/viz/reports.py
fitlins/workflows/base.py
setup.cfg

Follow-up to #166. Should have checked the text output before merging.

MNT: BIDSLayout.get() parameter "extensions" deprecated

---

fitlins/interfaces/bids.py

FIX: Expand entity whitelist

---

fitlins/interfaces/nistats.py

This change avoids unnecessary casts of BOLD data to float64, by hacking the `niimg.dataobj` parameters.
Related: https://github.com/neuroscout/neuroscout/issues/601

ENH: Avoid casting BOLD data to float64 if possible

---

.mailmap
.zenodo.json
CHANGES.md

@Shotgunosine I've added your Zenodo information from PyBIDS. Let me know if this is okay.
@adelavega Any blocks?

REL: 0.6.0 preparation

---

CHANGES.md

This is a proposed release. If you approve it, go ahead with it if you get a chance.

REL: 0.6.1 hotfix release preparation

---

.circleci/config.yml
setup.cfg

While we're waiting on https://github.com/nedbat/coveragepy/issues/915, let's get CI back up and running...

FIX: Blacklist coverage >=5

---

fitlins/cli/run.py
fitlins/interfaces/bids.py

FIX: Validate BIDS datasets except when searching for models

---

fitlins/workflows/base.py

Closes #219 
Running a model now to see if it fixes it

Add FEMA as key value to stat path_pattern

---

fitlins/interfaces/nistats.py
fitlins/workflows/base.py

- Also output log-likelkihood (logL) from model

Add logL as model output

---

fitlins/cli/run.py
fitlins/utils/bids.py

Closes #273 
Adds estimator selected to the `dataset_description.json`

ENH: Writeout estimator to derivative description

---

.zenodo.json
CHANGES.md
fitlins/tests/test_outputs.py

I think it's about time for a release.
I've included #276 in this so let's wait to merge that, first.
Also want to wait on #278 if it looks easy.
I updated the CHANGELOG and .zenodo.
I couldn't find @leej3's ORCID. Added @jdkent (please confirm affiliation ;)

REL: 0.9.0

---

setup.cfg

MNT: Upgrade pybids to 0.13

---

CHANGES.md

Release with new pybids and nilearn pins

REL: 0.9.1

---

CHANGES.md

REL: 0.9.2

---

fitlins/interfaces/afni.py

Fixes #320 by assuming constant name is: `constant`

FIX: Unreliable constant column name finding

---

fitlins/cli/run.py
fitlins/utils/bids.py
fitlins/viz/reports.py

1) Use absolute paths for database files
2) Sort subjects to avoid rerunning nodes due to nondeterministic ordering
3) Make directory in degenerate case where it was not already made

FIX: Minor fixes

---

.pre-commit-config.yaml
fitlins/__about__.py
fitlins/__init__.py
fitlins/__main__.py
fitlins/cli/run.py
fitlins/conftest.py
fitlins/generate_dset.py
fitlins/interfaces/abstract.py
fitlins/interfaces/afni.py
fitlins/interfaces/bids.py
fitlins/interfaces/nistats.py
fitlins/interfaces/tests/test_afni.py
fitlins/interfaces/utils.py
fitlins/interfaces/visualizations.py
fitlins/tests/conftest.py
fitlins/tests/test_outputs.py
fitlins/utils/bids.py
fitlins/utils/config.py
fitlins/utils/strings.py
fitlins/viz/contrasts.py
fitlins/viz/corr.py
fitlins/viz/reports.py
fitlins/workflows/base.py
fitlins/workflows/tests/test_base.py
pyproject.toml
setup.py

Opening a new clean PR for restyling. I ll figure out how to merge this onto enh/actions once this is reviewed and approved. 
cc: @effigies

STY: Reformat to black, address flake8 issues

---

fitlins/interfaces/afni.py

cc: @effigies 
- Typo in line 339
- Restyling from pre-commit hooks

FIX: minor typo; missed restyling in afni.py

---

.readthedocs.yml
CHANGES.md
docs/conf.py
setup.cfg

Pushed release branch to the primary repository. Replaces #351.

REL: 0.10.1
