poldracklab/fitlins

fitlins/cli/run.py

Here's on option to address #6 
First, I removed the defaults from argparse and put them in `create_workflow`. This actually ends up not mattering much but IMO its cleaner and more explicit
More importantly, `main` now takes an `args` argument which is passed to `parse_args`. 
So now you can do the followng:
from fitlins.cli.run import main
main('dataset', 'output_dir', 'dataset', '--model=model.json')
and argparse will parse it. If no argument is passed, command line arguments (from sys) are passed in instead.
There's probably a better way to have a library CLI but for now this is good enough for me.

WIP: Allow importing and calling main

---

fitlins/base.py

Fix to #21 by creating the parent folder.
There may be a more elegant way to do this rather than just assuming that will be the first time the folder is needed. But for the time being this fixes the bug.

Create group level results dir - fix #21

---

Dockerfile
fitlins/__about__.py
fitlins/base.py
fitlins/cli/run.py
fitlins/interfaces/bids.py
fitlins/interfaces/nistats.py
fitlins/utils/bids.py
fitlins/viz/reports.py
fitlins/workflows/__init__.py
fitlins/workflows/base.py
requirements.txt
tox.ini

This PR tracks progress towards Nipype-ification of FitLins.
I'm starting to settle on an approach that mimics `SpecifyModel` but with a BIDS structure and possible selectors as inputs. The `session_info` objects at present contains sparse and dense components of the design, along with enough metadata to perform file selection (possibly through `BIDSDataGrabber` or a new, similar interface).
It probably makes sense to extend beyond the `SpecifyModel` API further to line up contrasts.
I anticipate the output of this will be shuttled to a `MapNode` to run all first-level estimates and contrasts.
My thoughts on second-level stats are not yet fully fleshed out. I think it would be good to try to head back to pybids and get to the point where we define the design and contrast matrices in such …

ENH: Rewrite first level analysis as Nipype workflow

---

fitlins/cli/run.py
fitlins/utils/bids.py

Following BEP 003:
> ## Derived dataset and pipeline description
> `<dataset>/derivatives/<pipeline_name>/dataset_description.json`
> 
> Keys:
> * HowToAcknowledge
> * PipelineDescription
>   * Name
>   * Version
>   * CodeURL
>   * DockerHubContainerTag
>   * SingularityContainerURL
>   * SingularityContainerMD5
> * SourceDatasetsURLs - a list of URLs to the source dataset(s) (mandatory)
> * SourceDatasetsVersions - a list of versions of the source dataset(s) (optional only if SourceDatasetsURLs specify the version unequivocally)
> * License
We should start adding docker hub tags and singularity URLs as environment variables when we build images. I've put in a stub to get the MD5, which will attempt to pull the `'version'` tag from Singularity Hub.
BIDS doesn't specify a field for …

ENH: Make dataset description

---

fitlins/cli/run.py

Derivative labels allow for multiple instances of the pipeline to be run with different parameters, identified by a human-readable label. The format is:
```
<outdir>/<pipeline>[_<derivative-label>]
```
In this case, `<pipeline>` is `fitlins`.
This is in accordance with discussions at the 2017 BIDS sprint, followed up by a brief [proposal](https://groups.google.com/d/msg/bids-apps-dev/xjqA_BhivMY/e-YOORvgAgAJ) on the [bids-apps-dev](https://groups.google.com/forum/#!forum/bids-apps-dev) mailing list.

ENH: Enable derivative label to tag pipelines

---

Dockerfile
fitlins/_version.py
fitlins/cli/run.py
setup.py

This places `sys.exit` in the `main` entry-point, to reduce the chance of unexpected exits for any external calling code.
This also restores preproc discovery, prioritizing that found in `<bids_dir>/derivatives`.
Other minor simplifications were also applied, such as allowing `argparse` to apply `os.path.abspath` to file inputs.
Closes #32 
Closes #34

RF: Simplify entry-points, restore preproc discovery

---

fitlins/interfaces/bids.py

Currently, we loop over BOLD files to get the TR. This creates an unnecessary dependency on the bold files being there (unless you use datalad), which would be nice to remove. Here, I loop over preproc files instead, and look for a matching sidecar of type='bold'.
This is untested.

Loop over preproc files, instead of raw BOLD files

---

fitlins/utils/bids.py

If its not found, don't try to open it, and instead set to empty dict.

Make dataset_description optional

---

Dockerfile
fitlins/__about__.py
fitlins/cli/run.py
fitlins/data/report.tpl
fitlins/interfaces/bids.py
fitlins/viz/reports.py
fitlins/workflows/base.py
requirements.txt

FIX: Limit NaN imputation and use mean non-zero value

---

fitlins/interfaces/nistats.py

Looks like the issue is that in the `session_info` dict, `None` value for `confounds` get turned into a string, and thus is not detected as a None. Here I also check against the string "None". 
Perhaps this should be resolved by ensuring the None value stays of that type, but I'm not sure why/how that is happening. I assume its a NiPype issue.
This allowed me to run a model with no confounds successfully. 
Closes #72

FIX: Correctly handle missing confounds

---

fitlins/cli/run.py
fitlins/interfaces/bids.py
fitlins/interfaces/nistats.py
fitlins/interfaces/visualizations.py
fitlins/viz/reports.py
fitlins/workflows/base.py

This PR has as its goal restoring report generation, and any stylistic/UX fixes that seem appropriate as I work toward that goal.
Currently reports are based on the presence of contrast matrix plots, which were removed in #84, so no reports are generated. Additional concerns:

FIX: Restore report generation

---

fitlins/interfaces/bids.py

I ran into an error when my repositories files did not contain the space in their name. I don't think it is necessary to have the space keyword to be compulsory. This PR gives an additional option for no specification of space, and will give a warning if several spaces are found.

BF: Allow for no space in the filename, complain if multiple spaces are found

---

Dockerfile
fitlins/__about__.py
requirements.txt

Update to post-0.7 pybids (use master to get grabbit 0.2.6 dependency). Also, constrain `pip<19` to avoid pypa/pip#6158.

MNT: Update dependencies

---

.mailmap
.zenodo.json
CHANGES.rst

Need to get this release out, as there are a bunch of changes that should be coming down the pipeline shortly, and it shouldn't all be mixed up with pybids 0.7/Derivatives RC1 compatibility stuff.
@AdinaWagner Are you okay with being listed on Zenodo releases?

REL: 0.2.0

---

README.rst

Included optional smoothing in README. Removed info about not supporting smoothing.

DOC: Update README with latest help text, remove smoothing disclaimer

---

fitlins/cli/run.py
fitlins/data/report.tpl
fitlins/viz/reports.py
fitlins/workflows/base.py

Beginning work on #90.
First step is creating a figures folder that can be parameterized by run, session or subject. This reduces the clutter of keeping figures and statistical maps together, and also provides a filesystem object (the `figures/` directory) that should one-to-one match with report files that need generating.

FIX: Restore level 2+ reports

---

CHANGES.rst
CODE_OF_CONDUCT.md
CONTRIBUTING.md
fitlins/__init__.py

Now's a good time for small annoying bug fixes. It seems unlikely I'll get anything major in before the end of day, although #131 has a chance.
@adelavega I'd prefer not to break neuroscout, so if you can check master, please do.
@mgxd @satra If you've got anything please let me know.

REL: 0.3.0

---

fitlins/interfaces/nistats.py

Following nistats/nistats#321.

FIX: mask parameter to FirstLevelModel is deprecated for mask_img

---

.circleci/config.yml
fitlins/interfaces/bids.py
fitlins/viz/reports.py
setup.cfg

Fixes #179 
Need to wait on pybids release so that Circle pulls the new version of pybids that causes this problem.
Also depends on #178 which has other fixes.

FIX: Don't validate generated paths

---

fitlins/interfaces/nistats.py

Fmriprep 1.5.0's cosine columns don't have an underscore in them.

FIX: Recognize cosine columns without underscores

---

fitlins/interfaces/abstract.py
fitlins/interfaces/nistats.py
fitlins/workflows/base.py

This is a first pass at abstracting interfaces, intended to ease #171, which reuses the nistats design matrix for the time being.
The goal is to try to move our interfaces away from the specifics of nistats to the inputs and outputs inherent to the processes at each stage. We may want to further refine the scope, or increase the range of abstract processes. For example, we could reduce the estimator outputs to effects, variances and metadata, and move stat, p and Z maps to a separate interface, which AFNI could implement with `3dPval`.

RF: Abstract interfaces to simplify swappability

---

CHANGES.md
fitlins/cli/run.py
fitlins/data/full_report.tpl
fitlins/interfaces/abstract.py
fitlins/interfaces/bids.py
fitlins/interfaces/nistats.py
fitlins/interfaces/utils.py
fitlins/viz/reports.py
fitlins/workflows/base.py

Fixes #176 
- Behavior is toggled by CLI flag (`--drop-missing`). By default, it crashes.
- In `FirstLevelModel`, empty columns are detected in design matrix.
- In higher level models, dropping missing inputs is handled by `MergeAll`.

ENH: Drop missing model inputs

---

fitlins/workflows/base.py

Fixes #189 
The `smoothing_fwhm` was applied to model before the next level's model was created. This resulted in the `Subject` level inputs being smoothing rather than `Dataset`

FIX: Set smoothing_fwhm after creating next level. Fixes #189

---

fitlins/workflows/base.py

Fix BIDSelect confusion between Nifti and JSON

---

examples/models/ds000003/models/model-001_smdl.json
fitlins/interfaces/bids.py
fitlins/interfaces/nistats.py
fitlins/workflows/base.py

Closes #194 
Only added an example model so far

[WP] Add F-tests

---

.circleci/config.yml
fitlins/cli/run.py
fitlins/workflows/base.py

ENH: Add memory estimate for first-level models, enable memory management

---

fitlins/cli/run.py

Change `-v` from `--version` to `--verbose`. Add `-q` flag as well.
Also set the log levels on nipype logs, which were for some reason silent. I'm guessing there was a change in default behavior in a recent nipype release...

UX: Update logging levels

---

fitlins/cli/run.py
fitlins/workflows/base.py

As it gets handled in the initial layout build
fixes #201

FIX: Don't pass ignore and force index to init_fitlins_wf

---

fitlins/interfaces/bids.py

Related issue: https://github.com/bids-standard/pybids/issues/557
Stems from having `validate=False`, which we only used to do when necessary, but now is applied across the whole master Layout

Add desc=preproc as filter when finding preproc BOLD files

---

fitlins/interfaces/nistats.py

Unfortunately, I didn't test this thoroughly enough, and the update on the `FEMA` input file indexing was incorrect. I reverted to a more clear/optimized version of my original logic.
Consider the following:
```
filtered_effects = ['/tmp/tmpe9vfsb1a/fitlins_wf/l1_model/mapflow/_l1_model0/text_effect_size.nii.gz',                                                                                                                         
'/tmp/tmpe9vfsb1a/fitlins_wf/l1_model/mapflow/_l1_model0/rmse_effect_size.nii.gz',                                                                                                                         
'/tmp/tmpe9vfsb1a/fitlins_wf/l1_model/mapflow/_l1_model0/speech_effect_size.nii.gz', …
```

FIX: FEMA input index should filter on rows, not columns.

---

setup.cfg

- Specifically, this should fix the Replace transformation

MNT: Bump pybids to 0.10.2

---

.circleci/config.yml

* Remove "-it" from docker runs to avoid the `^@^@` characters that often happen.
* Add verbosity to FitLins runs

CI: Improve outputs

---

setup.cfg

Sphinx 3.0 was release which was causing the doc tests to fail. Downgrading to 2.4 and pinning latest versions of other doc packages.

FIX: Downgrade Sphinx to <3.0

---

fitlins/interfaces/nistats.py

FWIW I rebuilt the image and without this fix seemed to work so I think it's probably dependent on pandas versioning. 
Still, doesn't hurt to do this.

Only drop modulation if needed

---

fitlins/interfaces/bids.py
fitlins/interfaces/nistats.py

Fix #257 
See also: https://github.com/neuroscout/neuroscout-cli/issues/111
- Given that fitlins interprets the BIDS Stats Model, I don't think any convolution should be happening if you don't ask for it. 
Currently it is, for sparse variables. 
- Alternatively, we could move away from sparse variables entirely, and fully create the design matrix in pybids, and not even pass any sparse variables (and even throw an error if there are any?)

FIX: Sparse matrix should be in long format, and HRF should be None by default

---

.circleci/config.yml

I made CI take a long time in #262 , and now I'm going to try to fix it.

[CI] Make faster?

---

fitlins/interfaces/afni.py

Fix afni contrast bool

---

fitlins/cli/run.py
fitlins/generate_dset.py
fitlins/interfaces/bids.py
fitlins/interfaces/nistats.py
fitlins/interfaces/visualizations.py
fitlins/utils/bids.py
setup.cfg

Drop nistats, put some pybids warnings to rest.
Closes #261.

MNT: Update PyBIDS and nilearn

---

fitlins/workflows/base.py

It should not be required to specify a task in a model (i.e. run a model across all tasks)
I modified the `PATH_PATTERNS` to make task optional. 
Need to test a bit more.

ENH: modify path patterns to make task optional

---

fitlins/cli/run.py
fitlins/interfaces/abstract.py
fitlins/interfaces/nistats.py
fitlins/workflows/base.py

Closes #274 
I debated if this should be a CLI flag, but honestly the CLI is already feeling a bit bloated, and I think automatically doing anything to do the design matrix is against the design philosopy of BIDS StatsModel / fitlins.

Make drift model configurable via CLI

---

fitlins/viz/reports.py

The entity key `res` causes a conflict in the report generation.
I'm simply excluding it from being passed on (currently running a model to confirm that this fix works)

Exclude res from report entities

---

setup.cfg

Meanwhile pybids 0.13.x maintenance branch is released, pin to github branch for development

Temporarily pull pybids from github maintenance branch

---

fitlins/cli/run.py

This makes it so that `fitlins` is always display as the program name when the ArgParse throws an error.
This is needed because the way I call Fitlins (from neuroscout-cli), it will display "neuroscout" as the name of the program, which is confusing.
neuroscout passes unrecognized arguments forward to fitlins, and it's useful to get a direct error from fitlins' ArgParse to understand how to correct the call to neursocout-cli.

ENH: Set prog name to fitlins, regardless of which CLI program was called

---

.github/workflows/workflows.yml
setup.cfg
tools/ci/check.sh

MNT: Use latest coverage
